### ISSUE TITLE
请问下2017如果要组NAS用什么芯片和CPU比较好呢？

### ISSUE THREAD

**Issue by yimeng** [soulteary/Home-Network-Note#10]
用途：软路由+自己做点实验跑跑docker啥的。
能省电最好：不能省多几个钱也没关系
家里有个大机箱，想用上。

**Comment by rzcat** [comment]
J3455

**Comment by soulteary** [comment]
@yimeng 节能角度考虑，N、J 开头的CPU都可以，如果有塔式机箱，个人建议上G、E系的自己能承受的CPU会更合适，主要能源消耗不在CPU空载，而在硬盘运转上。（全SSD除外）

如果你需要额外的虚拟化，请考虑能开VT-X的CPU，以及能直通的硬件。
Docker应用不复杂、使用量少、计算不密集的话，年末买年初的硬件就👌，节约的钱买UPS。
