### ISSUE TITLE
你的网络拓扑疑问

### ISSUE THREAD

**Issue by ritaswc** [soulteary/Home-Network-Note#11]
同样是码农，我是PHPer，电脑维修经验7年，幸会幸会。
先说一下我的情况：我一直在外面工作，不是在老家，也就没有像你那么折腾，所有没有买很多硬件。毕竟家里穷，没这个胆子把工资随便浪掉。不过平时一直有研究各种IT知识，知识库还是很广泛的。MacBook、大疆、网络、Linux、树莓派、BT服务器、虚拟化等等，有机会可以加我好友 微信:maidou__xhu

我看到你有三个路由器，主路由是什么牌子的？看到你有代码机器、资源机器，为什么不用有线连接，是因为家里装修办不到么，还是你搞不定双绞线，手动大笑😁

**Comment by soulteary** [comment]
折腾者握爪先。

主路由最开始是wndr4300，后来换成了小米mini一代，再后面使用了很久newifi d2，现在在使用5300gt。

家里服务器是有线链接，专门放了两只机柜收纳它们，可能图标记不清楚吧😄。

ps: 提到配线，想了一下上一次配线是高中了，现在配可能真记不得线序了，毕竟十年过去了，唏嘘。
