### ISSUE TITLE
scripts/ip-data-split.sh 好像有些问题

### ISSUE THREAD

**Issue by UptonEdward** [soulteary/Home-Network-Note#14]
首先很感谢作者写出这么一篇文章手把手教我们怎么去创建一个免费的IP数据库，我看了也有很多收获，解决了一个长久困扰我的问题。
但是在尝试跟随作者的方法去对IP分类的时候，我发现在`sh split.sh`之后，DE和其他一些地区的CIDR出现了问题：
`196.10.61.0/18.8707`出现了类似于这样的错误的CIDR。

复现步骤：
```
sh download.sh
sh verify.sh
mkdir data
mv delegated-* data
cat data/delegated-*-latest | sort | uniq > data/all.txt
cat data/all.txt | awk '$1 ~ /^[^;#]/' > data/pure.txt
cat data/pure.txt | awk -F '|' '{print $2}' | sort | uniq | awk '{ if (length($0) == 2) print }' > data/region.txt
sh split.sh
```
我分别在Linux和macOS上都测试了一下，都出现了一样的问题。但实在没有找到问题出在哪里，于是来issue区向您求助。

**Comment by UptonEdward** [comment]
截止6月11日下午两点，一共有678个CIDR处理出现问题，而且发现于FR、NL、PL、IE、DE、ES、SE、US、IL、GB、CH等多个地区。
完整的错误CIDR列表如下：
https://gist.github.com/UptonEdward/32b3f4fad175985b8ea99234096a9e7c

**Comment by soulteary** [comment]
感谢反馈问题  @UptonEdward ，根据你的帖子内容，我发现确实有这个问题。

---

出现这个问题的原因是这些区域分配的“数量”不是 CIDR Mask 整数导致（参考 CIDR Map）...

```bash
ripencc|CH|ipv4|91.216.83.0|768|20100512|assigned|dda39a5e-9b71-4fce-b6fd-d857491ce5e6
```

想解决也不难，调整一下计算方式就好，比如可以把简单的通过 `32-log($5)/log(2)` 计算 cidr 更换为通过 range to cidr mask。


----

我会重写写一个小程序来处理这些数据，:D

**Comment by soulteary** [comment]
```bash
ripencc|CH|ipv4|91.216.83.0|768|20100512|assigned|dda39a5e-9b71-4fce-b6fd-d857491ce5e6

cidr 91.216.83.0/24
cidr 91.216.84.0/23
Count 768
```

看起来没有什么问题，内容将会以续篇的形式随后面的内容一起发布 :D

**Comment by soulteary** [comment]
程序：https://github.com/soulteary/Home-Network-Note/commit/e4ff73fb1528fca613b0a8a34e6a8d6f995a6998
文章稍后发布 :) @UptonEdward
