### ISSUE TITLE
新出了N3710 cpu

### ISSUE THREAD

**Issue by liuguojun** [soulteary/Home-Network-Note#6]
或者J3710  淘宝已经有对应主板了，华擎的，感觉不错，可惜能DC-ATX电源

**Comment by soulteary** [comment]
=，=，多谢提醒！

我把数据列一下，以供后面的人参考：

**网站对比：** [CPUBOSS](http://cpuboss.com/cpus/Intel-Pentium-N3700-vs-Intel-N3710)
**ARK链接：**

- http://ark.intel.com/zh-cn/products/87261/Intel-Pentium-Processor-N3700-2M-Cache-up-to-2_40-GHz?q=Intel%C2%AE%20Pentium%C2%AE%20Processor%20N3700%20(2M%20Cache,%20up%20to%202.40%20GHz)
- http://ark.intel.com/zh-cn/products/91830/Intel-Pentium-Processor-N3710-2M-Cache-up-to-2_56-GHz?q=Intel%C2%AE%20Pentium%C2%AE%20Processor%20N3710%20(2M%20Cache,%20up%20to%202.56%20GHz)

N3710主频要高于N3700
