### ISSUE TITLE
资源备份有什么开源的介绍

### ISSUE THREAD

**Issue by clanaid** [soulteary/Home-Network-Note#8]

**Comment by soulteary** [comment]
这个要分好多类型的文件

- 个人敏感数据 （btsync，非开源，但是买了授权，且全平台客户端支持 + rsync（开源）
- 个人代码数据 （github，算开源嘛，买private repo + gitlab ce +rsync
- 个人照片 （dropbox+btsync+rsync+冷备+偶尔time machine
- 大型资源类文件 （samba这类nfs加定时任务cp一份
- 某些游戏或不重要文件，找个百度云的client，定时sync就好

**Comment by clanaid** [comment]
我现在暂时的需求是搭个软路由和nas一体的，有什么硬件推荐的

**Comment by soulteary** [comment]
@clanaid 根据数据量，带机量，上自己能负担，或者最大化利用自己手头的具有可靠性的设备就好了。

n3700，n35x0，奔腾板子就不错，当然，如果有可能，直接上微塔也是不错的选择。（我感觉我又能晒图了）

如果有特殊的技术取向，esxi，需要考虑硬件能够vt-d，etc

**Comment by clanaid** [comment]
@soulteary 微塔是什么意思

**Comment by soulteary** [comment]
@clanaid OptiPlex 9020 这类机器你值得拥有。比路由大不了多少，目前性价比还不错。

其实gen8也是微塔，不过入手gen8前要想清楚你对于计算的需求，因为购置硬件后升级cpu、把可插的硬盘槽填满是一个比较费钱的事，哈哈

**Comment by clanaid** [comment]
@soulteary 我还是先买折腾下奔腾板子先2333333，微塔还是比较贵

**Comment by soulteary** [comment]
@clanaid 如果没有htpc的需求、以及不过度依赖usb接口，银行退下来的fx 160加固态也堪一用（不算存储，带内存200R左右就搞定，等价值也就是出去唱2个小时KTV了）。

此方案依赖你其他的设备有解码能力，eg：pad、phone、tv、projector...

**Comment by clanaid** [comment]
@soulteary 淘宝有卖？确实不需要htpc

**Comment by soulteary** [comment]
@clanaid 不知道现在还有没有，不过有心人总是能找到买的地方，毕竟一堆银行、证券要解决退役的机器呢。（有专业回收的人）

**Comment by clanaid** [comment]
@soulteary 那就算了，准备买j3160，在买个4口网卡来搭建

**Comment by soulteary** [comment]
issue长时间没有回复，先关闭，后续有需要再打开，或者重新开新issue也可以。
