### ISSUE TITLE
虚拟机使用了vmware没有使用virtualbox是什么原因呢？

### ISSUE THREAD

**Issue by superewe** [soulteary/Home-Network-Note#9]
vmware是需要版权的，virtualbox是免费的。
我看到你在使用vm，是因为vm的性能好？ 稳定？ 
希望你对比介绍下 vm和vb

谢谢！

**Comment by soulteary** [comment]
个人使用VirtualBox经历过一些小问题，比如跨系统导出的镜像文件不可导入、开启后影响其他同类型虚拟化软件、网络配置简陋、个别发行版使用缺少驱动...

而在OSX平台上，PD你懂的...

VMware有大量KB资料可查，对于硬件配置定制化极高，磁盘文件跨机器直接复用（多数情况下都不需要导出为镜像传输），再加上vmware偶有活动（双十一、黑五）可以抄个低价购入并升级pro，且是永久lic，临时跑一下还可以用VMware player无需安装整套虚拟机，如果是笔记本运行，在反复休眠唤醒后，崩溃率很低。

故VM+docker，基本满足各种应用的环境提供&环境隔离。

**Comment by evolutionjay** [comment]
膜拜大佬

**Comment by soulteary** [comment]
@evolutionjay 握爪

**Comment by soulteary** [comment]
issue长时间没有回复，先关闭，后续有需要再打开，或者重新开新issue也可以。
